FROM node:14.15.1 as builder
RUN apt update && apt-get install -y yarn

RUN mkdir app
WORKDIR app

COPY package*.json ./
RUN yarn install


COPY . ./
RUN rm -rf .env && mv .env.development .env && yarn build

ENV NODE_ENV=production
ENV HOST=0.0.0.0

EXPOSE 3000
ENTRYPOINT ["npm", "start"]

